### ISSUE TITLE
APP: Add an How To

### ISSUE THREAD

**Issue by TorbenU** [Echtzeitsysteme/mindroid#22]
- Explains which settings are necessary on the EV3 to connect the Phone with the EV3 successful.

**Comment by RolandKluge** [comment]
This is now documented in the current exercise sheet (see for instance: https://docs.google.com/document/d/1BjzzwK6wearpRj4Zn-Ls2egUhzGBlD0SAaHI-1XFvew/edit?usp=sharing)
