### ISSUE TITLE
APP/EV3: Support for Gyro sensor

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#39]
The 'turn' method should be supported by the (Lego or Nexus) gyro sensor.

**Comment by TorbenU** [comment]
EV3 Gyro sensor is supported. (introduced with https://github.com/Echtzeitsysteme/mindroid/commit/d84de11e569f48f07d142b24a0d378f0b0861e43)

**Comment by TorbenU** [comment]
https://github.com/Echtzeitsysteme/mindroid/commit/f63ac84028f47ddf13b58f272c0591c28bb0556f : turns now gyro (Lego) supported
