### ISSUE TITLE
APP: messenger can be null

### ISSUE THREAD

**Issue by TorbenU** [Echtzeitsysteme/mindroid#40]
- Start app and run robot --> nullponter exception
- Start app got to settings 'save settings', start robot --> No null pointer exception

**Comment by MarkusWeckesser** [comment]
@TorbenU please close if issue is resolved.

**Comment by TorbenU** [comment]
Should be fixed with https://github.com/Echtzeitsysteme/mindroid/commit/afe0c759401bb793ae39745b0a2909c1292c3e2a
