### ISSUE TITLE
Java-Editor: "Run" arrow is getting green after the first run

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#56]
How to reproduce:
(1) Press blue arrow
(2) Wait for build to complete
(3) Arrows turns green

**Comment by FeliciaRu** [comment]
Maybe we should contact Mr. Röhner about this, I didn't implement the blue button. (That was his idea when he added our Android Mode to the Java Editor)

**Comment by RolandKluge** [comment]
@FeliciaRu OK. Could you da that?

**Comment by FeliciaRu** [comment]
okay
