### ISSUE TITLE
App: Save last selection in state machine drop-down

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#69]

**Comment by TorbenU** [comment]
done in https://github.com/Echtzeitsysteme/mindroid/commit/6bd804ff164c327b8b466c49397edc197fba85a5

**Comment by TorbenU** [comment]
There may be still an issue, as the loaded selection will not be propergated properly

**Comment by TorbenU** [comment]
https://github.com/Echtzeitsysteme/mindroid/commit/e9156d0ac2dee337157063d1c000f94c7ea6d1fe
