### ISSUE TITLE
JE: Start app after deployment (assemble.bat)

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#70]
Can we extend the assemble.bat file to (re-)start the app after the deployment?

**Comment by FeliciaRu** [comment]
@RolandKluge It is possible to open an app if the package name is known:
`adb shell monkey -p org.mindroid.android.app -c android.intent.category.LAUNCHER 1`
Do you know how to get the package name?

**Comment by RolandKluge** [comment]
I have no experience with this tool.
Is it really necessary to add the "-c" option? (https://developer.android.com/studio/test/monkey.html)

**Comment by RolandKluge** [comment]
Could this one help?
https://stackoverflow.com/a/4567928

**Comment by FeliciaRu** [comment]
@RolandKluge 
> Could this one help?
> https://stackoverflow.com/a/4567928

The package name is needed there, too?

> Couldn't it be the package that contains the main Activity?

I think so, but I'm not sure.
The assemble.bat script operates in the folder that contains gradlew.bat. So I would need to search subfolders for MainActivity.java and use that path to get the package name. Should I do that?

**Comment by RolandKluge** [comment]
> So I would need to search subfolders for MainActivity.java and use that path to get the package name.
Now I see the problem: We want to be flexible and not hardcode the name of the activity.
Good question... Yes, we could establish the convention that that the main activity is always called *MainActivity.java*. Could you make the script robust against people violating the convention, i.e., just do nothing if *MainActivity.java* is missing?

**Comment by MarkusWeckesser** [comment]
You can derive the package name from the corresponding gradle build file from the property applicationId.

**Comment by FeliciaRu** [comment]
@MarkusWeckesser Which file do you mean? build.gradle is empty...

**Comment by MarkusWeckesser** [comment]
@FeliciaRu This one: mindroid/impl/androidApp/app/build.gradle

**Comment by FeliciaRu** [comment]
@MarkusWeckesser oh ok, found it.
New version of assemble.bat is here: https://github.com/Echtzeitsysteme/mindroid/blob/improve-HandyVerbinden/admin/Scripts/assemble.bat
cc @RolandKluge

**Comment by RolandKluge** [comment]
Thanks, confirmed to work well!
