### ISSUE TITLE
JE: Bug in parsing gradle output?

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#77]
When invoking "Starten" (green/blue triangle) in Android mode for the attached (non-compilable) code, I get the following error message: "Listenindex überschreitet das Maximum (-1)"
[MindroidLVL2.java.txt](https://github.com/Echtzeitsysteme/mindroid/files/1256557/MindroidLVL2.java.txt)

@FeliciaRu Could you contact Mr. Röhner on this issue?

**Comment by FeliciaRu** [comment]
I sent him an email.
