### ISSUE TITLE
API: myRobotID is not properly set

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#80]
* the value appears to be set only once by quering the RobotController.
* the attribute is publicly visible.

Solution: Create a getter ```getRobotId``` and delegate to the RobotController

This bug is of high priority because it blocks using the robot name as decision variable when writing "one program for multiple robots."

**Comment by TorbenU** [comment]
Test if last commit solves this issue

**Comment by TorbenU** [comment]
https://github.com/Echtzeitsysteme/mindroid/commit/62890db92559b485b3b1a8be44cc3c94adb2235c implements the testclass "TestMessageAccess" using the getRobotID() method as decision variable to run the same implementation on multiple robots. Therfore this issue seems to be solved.
