### ISSUE TITLE
Admin: Possible to deploy to multiple smartphones in parallel?

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#84]
Experience of the August 2017 workshop shows that it can be highly disturbing to repeatedly run the *HandyVerbinden* if you want to deploy the same app onto multiple devices.

We must find a better solution here.

The easiest way could be to provide a *HandyTrennen.bat* script that allows the student to deploy via USB.

The best solution would be to allow multi deployment via WiFi.

## Steps
- [ ] Convert bat script to Gradle script?
- [ ] Maybe use gradle extension for adb (or just the 'default' gradle script generated by IntelliJ). Inspiration: https://gist.github.com/MohsenK/18972afd9a89db827f4a
- [ ] We could assume that the Mindroid smartphones always receive the same IP address via DHCP --> no need for wired connection

## Useful resources
- Python scripts that do more or less what we want: https://thoughtsfromriga.wordpress.com/2014/07/21/control-apk-deployment-on-multiple-devices-simultaneously/
- Another stackoverflow post with some inspiration: https://stackoverflow.com/questions/8610733/how-can-i-adb-install-an-apk-to-multiple-connected-devices
- A *foreach* script for adb: 
   * https://gist.github.com/christopherperry/3208109
   * https://gist.github.com/thebagchi/df29ae862fc1c296dec2

**Comment by FeliciaRu** [comment]
As far as I know, deploying to multiple smartphones via usb should work with the current setup, did you test that?

Not sure if multi deployment via Wifi is possible, never tried it as I only have one device. If that's possible we could remove the part of HandyVerbinden.bat that always disconnects all wifi devices before connecting to a new one.

**Comment by RolandKluge** [comment]
> If that's possible we could remove the part of HandyVerbinden.bat that always disconnects all wifi devices before connecting to a new one.

This could be an option. We should identify the concrete problem first, of course.
As soon as you are back, I can give you a second smartphone.

**Comment by RolandKluge** [comment]
@FeliciaRu I added some resources that may be helpful to the issue description
