### ISSUE TITLE
JE: Place App Icon on Startscreen after installation

### ISSUE THREAD

**Issue by TorbenU** [Echtzeitsysteme/mindroid#85]

**Comment by RolandKluge** [comment]
This could help: http://viralpatel.net/blogs/android-install-uninstall-shortcut-example/

**Comment by MarcelMann** [comment]
not yet functional, places helloworldshortcut on homescreen

**Comment by MarcelMann** [comment]
now the shortcut starts the app, butindefinitely adds new shortcuts... (one at every app-start)

**Comment by MarcelMann** [comment]
maybe disable this feature, is not really important
