### ISSUE TITLE
Admin: Smartphones regularly lose connection to PC

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#86]
During the August 2017 workshop, the smartphones often lost connection to the PC.

We should try to reproduce this scenario with 4 (or more) smartphones.

**Comment by RolandKluge** [comment]
Maybe we could create a "quick reconnect" script because it appears that simply calling *adb connect* again should be sufficient in case the connection crashes: https://developer.android.com/studio/command-line/adb.html#wireless

**Comment by FeliciaRu** [comment]
I tested sending messages with 4 robots using the statemachine "TestMessagingWith4".

Findings:
1) The messages that are going back and forth stop being sent after 4-5 min. (The robots are supposed to continue sending messages but don't do that.) When the statemachines are stopped and restarted, they send messages for another ~5min. I couldn't find a reason for this...

2) I didn't experience connection loss between PC and smartphones, although using HandyVerbinden.bat only allowed me to connect 2 smartphones via Wifi at the same time. Whenever a third phone is connected via Wifi, the connection to another phone is dropped.
However, it is still possible to connect additional phones via USB while keeping 2 others connected via Wifi.

@RolandKluge

**Comment by RolandKluge** [comment]
@FeliciaRu 
Interesting... 
In 1.: Did you see any exceptions? Something must happen that stops the ping-pong.
In 2.: OK, is there any specific exception being thrown?

**Comment by FeliciaRu** [comment]
@RolandKluge 
1. There were none on screen, Here's the Android monitor output (I'm not sure if there's anything unusual, the messages stopped being sent at 16:01:09):
[AndroidMonitor.txt](https://github.com/Echtzeitsysteme/mindroid/files/1447936/AndroidMonitor.txt)

2. No, I only noticed it because HandyVerbinden.bat said "Anzahl verbundener Geräte: 2" instead of 3.

**Comment by RolandKluge** [comment]
@FeliciaRu 
Is the code already online? Maybe we can talk about this later today.

**Comment by FeliciaRu** [comment]
@RolandKluge 
The code for the statemachine is online now: 72b0183 (Though using getRobotID() does not work this way, I had to install the correct version of the state machine on the different phones manually)

[Here](https://gist.github.com/teocci/67b0771fc0faa4282c45db8e2fd4c107), they seem to be able to connect more than 2 devices via Wifi-ADB - I'm not sure if we did anything differently in Handyverbinden.bat, maybe someone should test this again on their pc, I only tested on my macbook (virtual machine)

**Comment by MarcelMann** [comment]
not an issue anymore
