### ISSUE TITLE
API: Refactoring to acess sensor values directly

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#87]
We should consider to remove some of the sensor value state machines and instead read the sensor values/messages directly from the knowledge component.

**Comment by TorbenU** [comment]
Since https://github.com/Echtzeitsysteme/mindroid/commit/2d0b2a80d701a22e812c938b30eb4884cdd2c711 it is possible to access the sensor values directly using the SensorProvider class.

**Comment by RolandKluge** [comment]
@TorbenU Sounds good. The implementation looks really tidy now.

Is LVL2API now to be seen as deprecated? If yes, you may remove it straight away if everything works (driving, turning, sensor evalution...)

**Comment by TorbenU** [comment]
https://github.com/Echtzeitsysteme/mindroid/commit/5c4c031350ca087116aabd60da20eac1d72db9cc accessing messages directly

**Comment by TorbenU** [comment]
Message and sensor access seems to work as intended now.
