### ISSUE TITLE
API: Check color mapping to improve quality of "Color ID" mode

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#88]
Apparently, the float IDs of colors have changed in the LeJOS API. This could also be the reason why the quality of color ID detection is really bad, currently.

**Comment by TorbenU** [comment]
Todo: Test new Mapping with Farbpalette.

**Comment by TorbenU** [comment]
Tested, but off by one. But works fine so far.

**Comment by TorbenU** [comment]
Works fine.
