### ISSUE TITLE
API/EV3: Improve forward() / backward() using synchronization

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#89]
Currently, the motors of the robot are controlled in an unsynchronized manner. This leads to the robot taking a very tiny turn whenever forward or backward are invoked.

Necessary steps from my view:
* Create "CreateMotorGroup" message
* Allow to combine motors into a group in APP
* Introduce "int speed" parameter into forward() and backward()

**Comment by TorbenU** [comment]
Note: It is not neccessary to group motors in app.
