### ISSUE TITLE
Provide square and (coordinated) wall ping-pong example based on refactored imperative API

### ISSUE THREAD

**Issue by RolandKluge** [Echtzeitsysteme/mindroid#95]
The next step should be to port the square +  wall ping-pong examples to the new ImperativeAPI and to improve the quality of the code.

- [x] What is the ```getImplementationID```? Is it the entry in the dropdown within the app?
- [x] Provide access to robot ID (via ```getRobotId``` method in ```ImperativeAPI```) to be able to write the same code for both robots.
- [x] Make all fields of ```ImperativeAPI``` private (only provide getters!)
- [x] Why do we need to have the the concrete and the abstract classes ```ImperativeWorkshopAPI``` and ```ImperativeAPI```
- [x] Get rid of all the old LVLxAPI classes if they are no longer needed

**Comment by TorbenU** [comment]
"What is the getImplementationID? Is it the entry in the dropdown within the app?" **yes** it is used as an identification of the implementation in the app.

**Comment by TorbenU** [comment]
_Why do we need to have the the concrete and the abstract classes ImperativeWorkshopAPI and ImperativeAPI:_ The ImparativeAPI specifies basic method an Imperative Implementation needs to run at all. The ImperativeWorkshopAPI extends ImperativeAPI and contains methods which are particular based on our Robot Setup of the workshop and therefore provides methods allowing to access sensor values and control the robot easily with a few lines of code.

**Comment by RolandKluge** [comment]
@TorbenU Thanks for clarifying.
